name: Sync repo with Ellx

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: matyunya/ellx-sync@master
        with:
          ellx-url: https://test-api.ellx.io
          key: ${{ secrets.ELLX_KEY }}
